### ISSUE TITLE
스프링 데이터 JPA 벌크로 처리할 수 있는 코드 찾아서 수정하기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#125]
## 📝 개요
- 스프링 데이터 JPA 벌크로 처리할 수 있는 코드 찾아서 수정하기

## ✅ To-Do
- [ ] 커스텀 어노테이션 list 검사하는 쿼리
- [ ] service 클래스
- [ ] 성능 비교 테스트 꼭 하기!!

## 👀 ETC
- 참고자료 등 기타 내용 작성
- [[JPA] 벌크 연산(Bulk Operation)이란?](https://dev-coco.tistory.com/169)

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요

**Comment by choign3123** [comment]
벌크 처리보단, batch 처리를 고려하는게 유지보수 측면에서 더 나을 것 같음.
