### ISSUE TITLE
paging 응답, 요청값 수정하기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#132]
## 📝 개요
- 굳이 원래 0에서 시작하는걸 1로 바꿀 이유는 없을 것 같음.
- 프론트에서 화면에 page 번호를 1부터 띄워야 되는 것도 아니며, 매번 백에서 page에 -1을 해줘야 하는 번거로움도 있음.

- 현재 페이지 num -> '현재 페이지에 나올 데이터 수' 변경. 이 값이 좀더 의미있을 것 같음.

## ✅ To-Do
- [x] paging 시작 1->0으로 바꾸기
- [x] meta 값 변경하기

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
