### ISSUE TITLE
마이페이지 통계값 구하는 SQL 에러

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#133]
## 📝 개요
- 마이페이지 '카테고리 개수' '스크랩 개수' 통계치 구하는 SQL에 오류가 있음

## ✅ To-Do
- [ ] 마이페이지 응답값 에러 수정

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
