### ISSUE TITLE
스크랩 최대 생성 개수 변경

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#137]
## 📝 개요
- 정책 변경에 따른 스크랩 최대 생성 개수 변경

## ✅ To-Do
- [ ] 스크랩 최대 생성 개수 변경하기 (100 -> 1000)

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
