### ISSUE TITLE
스크랩 즐겨찾기하기 메소드 잘못된 코드 수정하기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#138]
## 📝 개요
- 앞에 this를 붙여 해당 클래스의 필드임을 나타내야 함
```
public boolean toggleFavorite(boolean isFavorite){
        **isFavorite** = isFavorite; // 여기!
        return isFavorite;
    }
```

## ✅ To-Do
- [x] 스크랩 즐겨찾기하기 메소드 잘못된 코드 수정하기

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
