### ISSUE TITLE
로그아웃시 이전에 발급한 토큰은 사용 못하게 막기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#141]
## 📝 개요
- 로그인한 날짜를 기준으로, 이전에 발급된 토큰이면 접근을 막으면 됨.

## ✅ To-Do
- [ ] 로그아웃시 이전에 발급한 토큰은 사용 못하게 막기
- [ ] 보통 로그아웃을 구현하기 위해 redis를 쓰던데, 이유 알아보기.

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요

**Comment by choign3123** [comment]
구현 불가능하다 판단.
이유 2가지:
1. 토큰 발급일은 ms단위까지 저장되지 않음. 반면 db에 저장되는 loginDate 필드는 ms초 단위까지 저장됨 (둘다 utils.Date로 같은 클래스일때도) 그래서 로그인 한 이후에 토큰이 발급된 것처럼 만들어야 하지만, 어떻게 하든 로그인 하기 이전에 토큰이 발급된 것처럼 됨.
2. 1번 문제를 해결하기 위해, db에 ms단위를 제거한 후 저장한다 해도 다른 쟁점이 발생. 무조건 member의 loginDate를 업데이트 한 후에 토큰을 발급해야하는 순서가 생김. 이 순서는 표면상으로 명시하기가 어려움. 토큰 생성 메소드를 보기전까진 순서가 지켜져야 한다는 것을 알기 어려움.

로그아웃을 구현하기 위해 redis를 쓰는 이유가 있었음..

**Comment by choign3123** [comment]
구현 불가능하다 판단.
이유 2가지:
1. 토큰 발급일은 ms단위까지 저장되지 않음. 반면 db에 저장되는 loginDate 필드는 ms초 단위까지 저장됨 (둘다 utils.Date로 같은 클래스일때도) 그래서 로그인 한 이후에 토큰이 발급된 것처럼 만들어야 하지만, 어떻게 하든 로그인 하기 이전에 토큰이 발급된 것처럼 됨.
2. 1번 문제를 해결하기 위해, db에 ms단위를 제거한 후 저장한다 해도 다른 쟁점이 발생. 무조건 member의 loginDate를 업데이트 한 후에 토큰을 발급해야하는 순서가 생김. 이 순서는 표면상으로 명시하기가 어려움. 토큰 생성 메소드를 보기전까진 순서가 지켜져야 한다는 것을 알기 어려움.

로그아웃을 구현하기 위해 redis를 쓰는 이유가 있었음..
