### ISSUE TITLE
토큰 재발급 로직 수정

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#142]
## 📝 개요
- 기존: 
토큰 유효성 검사 API를 통해 토큰 유효성 검사 + 재발급이 함께 이뤄졌음
그 과정에서 토큰이 만료되지 않았음에도, 시간이 얼마 안남았을 때 다시 재발급해주는 과정이 들어감.
- 수정: 
평소엔 일반적으로 API 사용. 
그러다가 토큰 만료 에러 응답이 가면, 프론트가 토큰 재발급 API를 사용해 다시 토큰을 갱신받도록 로직 수정하기

## ✅ To-Do
- [x] 토큰 재발급 로직 수정

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
