### ISSUE TITLE
토큰 재발급이 가능한 경우와, 그렇지 않은 경우 statusCode 응답 분리하기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#144]
## 📝 개요
- 토큰 재발급으로 해결이 가능한 경우: 토큰이 만료된 경우(401 에러)
- 토큰 재발급으로 해결이 불가능한 경우: 나머지 케이스(406 에러)
- 이러면 프론트에서 401 에러일 때만 토큰 재발급 요청을 보내면 됨.

## ✅ To-Do
- [x] 토큰 재발급이 가능한 경우와, 그렇지 않은 경우 statusCode 응답 분리하기

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
