### ISSUE TITLE
MemberStatus에서 UNREGISTER 상태 삭제하기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#145]
## 📝 개요
- 회원 탈퇴시 DB에서 완전 삭제로 정책 결정함에 따라, UNREGISTER 상태 필요 없어짐.

## ✅ To-Do
- [x] MemberStatus에서 UNREGISTER 상태 삭제하기

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
