### ISSUE TITLE
토큰 유효성 검사 API 수정하기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#147]
## 📝 개요
- 토큰 재발급하는 로직 변경함에 따른, 토큰 유효성 검사 API 요청 응답값 수정하기

## ✅ To-Do
- [x] 토큰 유효성 검사 API 수정하기

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
