### ISSUE TITLE
HttpRequestMethodNotSupportedException 에러 핸들링하기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#149]
## 📝 개요
- HttpRequestMethodNotSupportedException 에러 핸들링하기
- 뭉뜽그린 '서버 에러' 대신, 해당 메소드는 지원하지 않는다고 구체적으로 이유 알려주기

## ✅ To-Do
- [ ] HttpRequestMethodNotSupportedException 에러 핸들링하기

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
