### ISSUE TITLE
Service클래스 단위 테스트 코드 작성하기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#152]
## 📝 개요
- Service 클래스에 대해 단위 테스트 코드 작성하기

## ✅ To-Do
- [ ] Service 클래스에 대해 단위 테스트 코드 작성하기

## 👀 ETC
- [단위 테스트 작성 방법](https://mangkyu.tistory.com/145)

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
