### ISSUE TITLE
카테고리 삭제시 발생하는 에러 고치기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#153]
## 📝 개요
- 카테고리를 삭제할 때, 카테고리에 속한 스크랩도 삭제하라고 요청했으나, 삭제되지 않는 문제 해결하기
- 단위 테스트 하다가 발견

## ✅ To-Do
- [ ] 카테고리 삭제시 발생하는 에러 고치기

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
