### ISSUE TITLE
커스텀 어노테이션 없이 validation 처리하기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#161]
## 📝 개요
- Controller의 커스텀 어노테이션에서 엔티티를 조회해 우선 validate(엔티티 존재&유효 여부)를 처리하니, Service 클래스에서 해당 엔티티들이 조회되어 검증되었는지 확인하려면 계속 Controller를 확인해야됨.
- 이로인해 야기되는 문제는 2가지
1. Service 계층에서 로직을 작성할 때 Controller도 확인해야 함.
2. Controller에서 조회한 데이터를 Service 계층에서 또 조회하기도 함. (단건 조회는 상관 없으나 여러건 조회할 때 findAllById()로 조회해서 쿼리가 2번 나감.)

## ✅ To-Do
- [ ] 커스텀 어노테이션 없이 validation 처리하기

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
