### ISSUE TITLE
Scrap/TrashScrap, Category/TrashCategory 엔티티 분리하기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#162]
## 📝 개요
- 휴지통에 버려진 스크랩을 다른 엔티티로 관리할지, status로 관리할지 고민이 됨.
- status로 관리하게 되면, 모든 스크랩 조회에 계속 where절이 붙게됨. 만일 자칫해서 status 조건을 걸지 않으면 휴지통에 버려진 스크랩까지 조회되는 문제가 발생함. 또한 매 자정마다 휴지통에 버려진지 30일이 지난 스크랩은 hard delete 하려고 하는데, 그때 조회해야되는 스크랩 개수가 너무 많아짐.
- 그래서 Scrap과 TrashScrap을 다른 엔티티로 분리하여 관리해보기로 결정. 엔티티를 분리하면 관리가 더 편할 것 같음.

## ✅ To-Do
- [ ] Scrap/TrashScrap 엔티티 분리하기
- [ ] Category/TrashCategory 엔티티 분리하기

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
