### ISSUE TITLE
redis를 사용해 로그아웃 구현하기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#164]
## 📝 개요
- redis를 사용해 로그아웃 구현하기

## ✅ To-Do
- [ ] redis를 사용해 로그아웃 구현하기

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
