### ISSUE TITLE
컨트롤러 계층에 대해 테스트 코드 작성하기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#169]
## 📝 개요
- 컨트롤러 계층에 대해 테스트 코드 작성하기

## ✅ To-Do
- [ ] 컨트롤러 계층에 대해 테스트 코드 작성하기

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [ ] 담당자를 할당했어요
- [ ] 적절한 label을 달았아요
- [ ] 적절한 이슈 제목을 지었어요
