### ISSUE TITLE
클라이언트측에 보이는 RequestBody의 필드명과 서버측에서 쓰는 RequestBody의 필드명 일치시키기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#171]
## 📝 개요
- @JsonProperty를 사용해 클라이언트측에 보이는 필드명과 서버측에서 쓰는 필드명을 다르게 사용하니 2가지 문제가 발생했음.
  - 컨트롤러에 대한 테스트 코드 작성 불가 (테스트 코드를 작성할 때 Request Body는 서버측을 기준으로 만들수 있으나, 실제로 컨트롤러에 전달되어야 하는건 프론트측이어야해서)
  - 에러메시지의 필드명이 클라이언트측이 쓰던게 아닌 서버측이 쓰던거라 혼란 야기

## ✅ To-Do
- [ ] 클라이언트측에 보이는 필드명과 RequestBody의 필드명 일치시키기 (서버 기준으로 변경)

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
