### ISSUE TITLE
기획 변경에 따른 press selection에 대한 API 수정

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#173]
## 📝 개요
- press 선택에 대한 기획이 변경됨.
- paging 처리된 API에 대해 press-전체 선택을 처리하는 로직이 복잡했었음. 
  - 전체 선택이면 모든 데이터에 대해 처리, 전체 선택이 아니면 선택한 데이터에 대해서만 처리. 이게 다른 요구사항과 엮이면서 더욱 로직이 복잡해짐.
- 그래서 다른 서비스(네이버 메일, 카카오페이지)는 이를 어떻게 처리했는지 봐보니, '전체 선택'버튼을 실제 조회된 페이지에 대해서 까지만 선택되게끔 만들었음.
- 타 서비스와 같은 처리가 더 낫다고 판단. press 선택에 대한 API 로직 수정하기로 결정

## ✅ To-Do
- [x] press 선택에 대한 API 로직 수정

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
