### ISSUE TITLE
스크랩 검색하기 API 분리 및 조회범위 변경

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#175]
## 📝 개요
- 스크랩 검색하기 API 분리: (기존) 한 API 내에서 query parameter로 카테고리 또는 즐겨찾기됨에서의 검색을 구분하여 처리 -> (수정) '카테고리에서 검색하기'와 '즐겨찾기됨에서 검색하기'로 API 분리하기
  - API를 분리하여 기능의 담당을 명확하게 분리하기 위함.
- 기획 변경: (기존) 제목으로 검색 -> (변경) 제목 or 본문내용 or 메모로 검색

## ✅ To-Do
- [ ] 스크랩 검색하기 API 분리하기
- [ ] 검색되는 스크랩의 범위 넓히기

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [ ] 담당자를 할당했어요
- [ ] 적절한 label을 달았아요
- [ ] 적절한 이슈 제목을 지었어요
