### ISSUE TITLE
DB 타임존 문제 해결하기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#189]
## 📝 개요
- DB에 저장되는 시간이 한국 시간과 다름
- 애플리케이션 레벨에서 서버시간 맞출 예정 (우선 한국에만 런칭하기로 결정했기 때문)

## ✅ To-Do
- [ ] DB 타임존 문제 해결하기

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요

**Comment by choign3123** [comment]
기본 UTC로 저장. 클라이언트에 맞춰 시간을 변경하여 표현하는 것으로 정책 변경.
