### ISSUE TITLE
AWS Cloudwatch log 설정하기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#191]
## 📝 개요
- 로그 보려고 AWS ec2 인스턴스에 접속해서 명령어 쳐서 보기 번거로움.
- AWS Cloudwatch log 설정하기

## ✅ To-Do
- [ ] AWS Cloudwatch log 설정하기

## 👀 ETC
- [도커 공식 문서](https://docs.docker.com/engine/logging/drivers/awslogs/)

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
