### ISSUE TITLE
AWS CodeDeploy에 배포 실패한 문제 해결하기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#194]
## 📝 개요
- handle-existing-docker-container.sh에 docker 관련 명령어 중 권한 부여를 안한 부분이 있음. 
그래서 CodeDeploy에 배포 실패함.

## ✅ To-Do
- [ ] docker 관련 명령어 권한 부여하기.

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
