### ISSUE TITLE
Jacoco로 테스트 커버리지 확인하기

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#199]
## 📝 개요
- Jacoco로 테스트 커버리지 확인하기

## ✅ To-Do
- [ ] Jacoco로 테스트 커버리지 확인하기

## 👀 ETC
- [우테코 블로그](https://techblog.woowahan.com/2661/)
- [공식문서](https://docs.gradle.org/current/userguide/jacoco_plugin.html)

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
