### ISSUE TITLE
토큰의 유저 식별자값 통일을 통한 조회 로직 개선

### ISSUE THREAD

**Issue by choign3123** [choign3123/scrap-2024#200]
## 📝 개요
- 기존:
access 토큰: memberId와 snsType, snsId
refresh 토큰: snsType, snsId
- 두 토큰이 가진 값의 차이로 인해 member 조회 로직이 비효율적이고 복잡함.
memberId가 있으면 memberId로 조회하고, memberId값이 없으면 snsType과 snsId로 조회함.
- 그래서 토큰에 담을 유저 식별자값을 하나로 통일하고자 함.

## ✅ To-Do
- [ ] 토큰에 담을 유저 식별자값을 하나로 통일하기

## 👀 ETC
- 벨로그는 JWT토큰 사용 및 UUID값을 유저 식별자 값으로 사용
- 나머지 사람인, 쿠팡, 티켓링크는 세션ID 사용
- 특이하게 원티드는 memberId만 있어도 사용자 정보 조회 가능했음.

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 적절한 이슈 제목을 지었어요
